# https://blog.csdn.net/zhanglh046/article/details/78651993/ resource
spring:
  application:
    name: zuul-example
server:
  port: 8080

#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
  # 忽略所有请求
  ignoredServices: /**/hello/**
  routes:
    # 允许将服务名映射到heshengbang
#    zuul-example: /heshengbang/**
    users:
       path: /heshengbang/**
       url: http://localhost:8080

# 服务注册中心的配置内容，指定服务注册中心的Url
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/