spring:
  application:
    name: zuul-example-gateway
server:
  port: 9000

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/

#\u8FD9\u91CC\u7684\u914D\u7F6E\u8868\u793A\uFF0C\u8BBF\u95EE/it/** \u76F4\u63A5\u91CD\u5B9A\u5411\u5230http://localhost:7000/web/
zuul:
    routes:
       baidu:
          path: /**
          url: http://localhost:7000/
