spring:
  application:
    name: zuul-example-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/