# \u4ECE\u96F6\u5F00\u59CB\u7684Spring Security Oauth2 http://blog.didispace.com/spring-security-oauth2-xjf-1/
# http://lxgandlz.cn/404.html  REST API\u4F7F\u7528Spring Security+OAuth2\u505A\u6743\u9650\u63A7\u5236


server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    database: 0

logging.level.org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3