mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hsb.spring.boot.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  redis:
  # Redis服务器地址
      host: 127.0.0.1
  # Redis服务器连接端口
      port: 6379
  # Redis服务器连接密码（默认为空）
      password:
  # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  # 连接池中的最大空闲连接
        max-idle: 8
  # 连接池中的最小空闲连接
        min-idle: 0
  # 连接超时时间（毫秒）
      timeout: 0
      database: 5

logging:
  level:
    # 想要打出debug日志的包
    com.hsb.spring.boot.mapper: debug